# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'designed.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 310)
        MainWindow.setMinimumSize(QtCore.QSize(800, 310))
        MainWindow.setMaximumSize(QtCore.QSize(800, 310))
        MainWindow.setMouseTracking(False)
        MainWindow.setWindowTitle("Scanner")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.Urllabel = QtWidgets.QLabel(self.centralwidget)
        self.Urllabel.setObjectName("Urllabel")
        self.verticalLayout.addWidget(self.Urllabel)
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setObjectName("lineEdit")
        self.verticalLayout.addWidget(self.lineEdit)
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout.addWidget(self.pushButton)
        self.XSS_checkBox = QtWidgets.QCheckBox(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.XSS_checkBox.setFont(font)
        self.XSS_checkBox.setObjectName("XSS_checkBox")
        self.verticalLayout.addWidget(self.XSS_checkBox)
        self.ARP_checkBox = QtWidgets.QCheckBox(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.ARP_checkBox.setFont(font)
        self.ARP_checkBox.setObjectName("ARP_checkBox")
        self.verticalLayout.addWidget(self.ARP_checkBox)
        self.SQL_checkBox = QtWidgets.QCheckBox(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.SQL_checkBox.setFont(font)
        self.SQL_checkBox.setObjectName("SQL_checkBox")
        self.verticalLayout.addWidget(self.SQL_checkBox)
        self.XRF_checkBox = QtWidgets.QCheckBox(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.XRF_checkBox.setFont(font)
        self.XRF_checkBox.setObjectName("XRFC_checkBox")
        self.verticalLayout.addWidget(self.XRF_checkBox)
        self.Check_web_pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.Check_web_pushButton.setObjectName("Check_web_pushButton")
        self.verticalLayout.addWidget(self.Check_web_pushButton)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        self.Urllabel.setText(_translate("MainWindow", "URL"))
        self.pushButton.setText(_translate("MainWindow", "Set url"))
        self.XSS_checkBox.setText(_translate("MainWindow", "XSS"))
        self.ARP_checkBox.setText(_translate("MainWindow", "ARP-spoofing"))
        self.SQL_checkBox.setText(_translate("MainWindow", "SQL-injection"))
        self.XRF_checkBox.setText(_translate("MainWindow", "XRFC"))
        self.Check_web_pushButton.setText(_translate("MainWindow", "Check"))
