# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'designed.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 380)
        MainWindow.setMinimumSize(QtCore.QSize(800, 310))
        MainWindow.setMaximumSize(QtCore.QSize(800, 380))
        MainWindow.setMouseTracking(False)
        MainWindow.setWindowTitle("Scanner")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.verticalLayout.addWidget(self.lineEdit_2)
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setObjectName("pushButton_2")
        self.verticalLayout.addWidget(self.pushButton_2)
        self.Urllabel = QtWidgets.QLabel(self.centralwidget)
        self.Urllabel.setObjectName("Urllabel")
        self.verticalLayout.addWidget(self.Urllabel)
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setObjectName("lineEdit")
        self.verticalLayout.addWidget(self.lineEdit)
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout.addWidget(self.pushButton)
        self.bWAPP_checkBox = QtWidgets.QCheckBox(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.bWAPP_checkBox.setFont(font)
        self.bWAPP_checkBox.setObjectName("bWAPP_checkBox")
        self.verticalLayout.addWidget(self.bWAPP_checkBox)
        self.XSS_checkBox = QtWidgets.QCheckBox(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.XSS_checkBox.setFont(font)
        self.XSS_checkBox.setObjectName("XSS_checkBox")
        self.verticalLayout.addWidget(self.XSS_checkBox)
        self.SQL_checkBox = QtWidgets.QCheckBox(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.SQL_checkBox.setFont(font)
        self.SQL_checkBox.setObjectName("SQL_checkBox")
        self.verticalLayout.addWidget(self.SQL_checkBox)
        self.CRFC_checkBox = QtWidgets.QCheckBox(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.CRFC_checkBox.setFont(font)
        self.CRFC_checkBox.setObjectName("CRFC_checkBox")
        self.verticalLayout.addWidget(self.CRFC_checkBox)
        self.Check_web_pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.Check_web_pushButton.setObjectName("Check_web_pushButton")
        self.verticalLayout.addWidget(self.Check_web_pushButton)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        self.label.setText(_translate("MainWindow", "Auth"))
        self.pushButton_2.setText(_translate("MainWindow", "Auth"))
        self.Urllabel.setText(_translate("MainWindow", "URL"))
        self.pushButton.setText(_translate("MainWindow", "Set url"))
        self.bWAPP_checkBox.setText(_translate("MainWindow", "bWAPP"))
        self.XSS_checkBox.setText(_translate("MainWindow", "XSS"))
        self.SQL_checkBox.setText(_translate("MainWindow", "SQL-injection"))
        self.CRFC_checkBox.setText(_translate("MainWindow", "CRFC"))
        self.Check_web_pushButton.setText(_translate("MainWindow", "Check"))
